on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [definition_update]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout app
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install app dependencies
        run: bun install
      - name: Checkout keyboard definitions
        uses: actions/checkout@v4
        with:
          repository: freather-keyspensory/via-keyboards
          ref: master
          path: via-keyboards-src
      - name: Install keyboard definition dependencies
        working-directory: via-keyboards-src
        run: bun install
      - name: Build keyboard definitions
        working-directory: via-keyboards-src
        run: bun run build
      - name: Copy keyboard definitions
        run: |
          rm -rf public/definitions
          cp -R via-keyboards-src/dist public/definitions
      - name: Build
        run: bun run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_ACCOUNT_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
